services:
  rsspub:
    ports:
      - "3000:3000"
    image: harshit181/rsspub:latest
    volumes:
      - ${EPUBS_HOST_DIR:-./db}:/app/db
    environment:
      - RUST_LOG=info,html5ever=error
      - MALLOC_CONF=background_thread:true,dirty_decay_ms:1000,muzzy_decay_ms:1000
      - RPUB_USERNAME=${RPUB_USERNAME}
      - RPUB_PASSWORD=${RPUB_PASSWORD}
      - SECURE_OPDS=${SECURE_OPDS}
    restart: unless-stopped
