FROM rust:1.92.0-slim-trixie as builder

WORKDIR /usr/src/rpub
RUN apt-get update && apt-get install -y pkg-config build-essential && rm -rf /var/lib/apt/lists/*

COPY . .

RUN cargo build --features alternative-alloc

FROM debian:trixie-slim

WORKDIR /app

RUN apt-get update && apt-get install -y ca-certificates sqlite3 heaptrack libjemalloc-dev binutils procps --no-install-recommends && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/rpub/target/debug/rsspub /usr/local/bin/rsspub

COPY static /app/static

COPY rpub.db /app/rpub.db

EXPOSE 3000

ENV RUST_LOG=info
ENV MALLOC_CONF=prof:true,lg_prof_interval:30,lg_prof_sample:19,prof_prefix:/tmp/jeprof,prof_leak:true
ENV _RJEM_MALLOC_CONF=prof:true,lg_prof_interval:27,lg_prof_sample:19,prof_prefix:/tmp/jeprof,prof_leak:true

CMD ["rpub"]
